# Generated by Django 4.1.2 on 2022-11-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_categorymodel_genremodel_hostmodel_joinmodel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artistmodel",
            old_name="country",
            new_name="nationality",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="category",
        ),
        migrations.DeleteModel(
            name="CategoryModel",
        ),
    ]
