# Generated by Django 4.1.2 on 2022-11-12 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_country_artistmodel_nationality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genremodel",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genremodel",
            name="name",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genremodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.genremodel",
            ),
        ),
        migrations.AddField(
            model_name="genremodel",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="genremodel",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="songmodel",
            name="genre",
            field=models.ManyToManyField(to="core.genremodel"),
        ),
    ]
