# Generated by Django 4.1.2 on 2022-11-16 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_artistmodel_songs_joinmodel_accessibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagemodel",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="languagemodel",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="languagemodel",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="songmodel",
            name="song",
            field=models.FileField(
                default="default/default.png", upload_to="songs/mp3"
            ),
        ),
        migrations.AlterField(
            model_name="playlistmodel",
            name="image",
            field=models.ImageField(
                default="default/default.png", upload_to="playlist/image/"
            ),
        ),
        migrations.AlterField(
            model_name="songmodel",
            name="image",
            field=models.ImageField(
                default="default/default.png", upload_to="songs/image/"
            ),
        ),
    ]
