# Generated by Django 4.1.2 on 2022-11-16 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_languagemodel_created_on_languagemodel_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genremodel",
            name="image",
            field=models.ImageField(
                default="default/default.png", upload_to="genre/image/"
            ),
        ),
        migrations.AddField(
            model_name="languagemodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.languagemodel",
            ),
        ),
    ]
