# Generated by Django 4.1.2 on 2022-11-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_genremodel_image_languagemodel_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagemodel",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
