# Generated by Django 4.1.2 on 2022-11-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_languagemodel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songmodel",
            name="language",
        ),
    ]
