# Generated by Django 4.1.2 on 2022-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_songmodel_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="languagemodel",
            name="parent",
        ),
        migrations.AddField(
            model_name="songmodel",
            name="language",
            field=models.ManyToManyField(to="core.languagemodel"),
        ),
    ]
