# Generated by Django 4.1.2 on 2022-11-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_languagemodel_parent_songmodel_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistmodel",
            name="image",
            field=models.ImageField(
                default="default/default.png", upload_to="songs/artist/"
            ),
        ),
    ]
