# Generated by Django 4.1.2 on 2022-11-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_artistmodel_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artistmodel",
            name="parent",
        ),
    ]
