# Generated by Django 4.1.2 on 2022-11-26 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_remove_favouritemodel_name_remove_genremodel_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavouriteItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FavouriteListModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                ("name", models.CharField(default="Favorite List", max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="favouritesongmodel",
            name="favourite",
        ),
        migrations.RemoveField(
            model_name="favouritesongmodel",
            name="song",
        ),
        migrations.AddField(
            model_name="joinmodel",
            name="created_on",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="joinmodel",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="joinmodel",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="artistmodel",
            name="created_on",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="artistmodel",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="genremodel",
            name="created_on",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="genremodel",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="languagemodel",
            name="created_on",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="languagemodel",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="FavouriteModel",
        ),
        migrations.DeleteModel(
            name="FavouriteSongModel",
        ),
        migrations.AddField(
            model_name="favouriteitemmodel",
            name="favourite_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.favouritelistmodel",
            ),
        ),
        migrations.AddField(
            model_name="favouriteitemmodel",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.songmodel"
            ),
        ),
    ]
