# Generated by Django 4.1.2 on 2022-11-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_favouriteitemmodel_favouritelistmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genremodel",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="genremodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="genremodel",
            name="updated_on",
        ),
    ]
