# Generated by Django 4.1.2 on 2022-11-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_genremodel_created_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artistmodel",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="artistmodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="artistmodel",
            name="updated_on",
        ),
    ]
